[setting]
out_dir = "site/content"
preamble_ext = "zola-toml"
workers = 25
tags = []

# CIÊNCIAS HUMANAS
##################

## HISTÓRIA
[[authors]]
name = "Boletim do Tempo Presente"
feed = "https://periodicos.ufs.br/tempopresente/gateway/plugin/AnnouncementFeedGatewayPlugin/rss2"
tags = ["UFS", "História"]


# INTERDISCIPLINAR

## GÊNERO E SEXUALIDADE

[[authors]]
name = "Periódicus"
feed = "https://periodicos.ufba.br/index.php/revistaperiodicus/gateway/plugin/AnnouncementFeedGatewayPlugin/rss2"
tags = ["UFBA", "Gênero e Sexualidade"]


# CIÊNCIAS SOCIAIS APLICADAS
############################

## CIÊNCIA DA INFORMAÇÃO

[[authors]]
name = "Ciência da Informação - IBICT"
feed = "https://revista.ibict.br/ciinf/gateway/plugin/AnnouncementFeedGatewayPlugin/rss2"
tags = ["IBICT", "Ciência da Informação"]
